# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes Apache Tomcat and Process Types for WARs"
  homepage = "https://github.com/initializ-buildpacks/apache-tomcat"
  id = "initializ-buildpacks/apache-tomcat"
  keywords = ["java", "tomcat", "war"]
  name = "Initializ Buildpack for Apache Tomcat"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/apache-tomcat/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml", "resources/context.xml", "resources/logging.properties", "resources/server.xml", "resources/web.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    description = "the Tomcat access logging state"
    launch = true
    name = "BPL_TOMCAT_ACCESS_LOGGING_ENABLED"

  [[metadata.configurations]]
    build = true
    description = "the application context path"
    name = "BP_TOMCAT_CONTEXT_PATH"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable Tomcat's EnvironmentPropertySource"
    name = "BP_TOMCAT_ENV_PROPERTY_SOURCE_DISABLED"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the external Tomcat configuration archive"
    name = "BP_TOMCAT_EXT_CONF_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the external Tomcat configuration archive"
    name = "BP_TOMCAT_EXT_CONF_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the external Tomcat configuration"
    name = "BP_TOMCAT_EXT_CONF_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the external Tomcat configuration"
    name = "BP_TOMCAT_EXT_CONF_VERSION"

  [[metadata.configurations]]
    build = true
    default = "9.*"
    description = "the Tomcat version"
    name = "BP_TOMCAT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:tomcat:9.0.96:*:*:*:*:*:*:*"]
    id = "tomcat"
    name = "Apache Tomcat"
    purl = "pkg:generic/apache-tomcat@9.0.96"
    sha256 = "bf4ad04955457ad663157876461015437a7479546aec9a38840d736b3d70151f"
    source = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.96/src/apache-tomcat-9.0.96-src.tar.gz"
    source-sha256 = "f7b315c03628a320c19eefee192c555ded0529e600ea70803e759e760666090b"
    stacks = ["*"]
    uri = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.96/bin/apache-tomcat-9.0.96.tar.gz"
    version = "9.0.96"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:tomcat:10.1.29:*:*:*:*:*:*:*"]
    id = "tomcat"
    name = "Apache Tomcat"
    purl = "pkg:generic/apache-tomcat@10.1.29"
    sha256 = "93d92527d467fff094d45db1cabbe1a2cefb92979779a44f2a50d053b4155ce3"
    source = "https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.29/src/apache-tomcat-10.1.29-src.tar.gz"
    source-sha256 = "095f8da3b73e68e9654da1425ee856cab44287e3608949772c06a82c73d0cb57"
    stacks = ["*"]
    uri = "https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.29/bin/apache-tomcat-10.1.29.tar.gz"
    version = "10.1.29"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:cloudfoundry:tomcat-access-logging-support:3.4.0:*:*:*:*:*:*:*"]
    id = "tomcat-access-logging-support"
    name = "Apache Tomcat Access Logging Support"
    purl = "pkg:generic/tomcat-access-logging-support@3.4.0"
    sha256 = "b3452d5ffbf0652e0f44958a5cb306a961906280102e5fa1a15840d2ddb6bcc1"
    source = "https://repo1.maven.org/maven2/org/cloudfoundry/tomcat-access-logging-support/3.4.0.RELEASE/tomcat-access-logging-support-3.4.0.RELEASE-sources.jar"
    source-sha256 = "857098bf8f03c38270403b91489346a13c997dcbf466de15da33f4a370e00a10"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/org/cloudfoundry/tomcat-access-logging-support/3.4.0.RELEASE/tomcat-access-logging-support-3.4.0.RELEASE.jar"
    version = "3.4.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/cloudfoundry/java-buildpack-support/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:cloudfoundry:tomcat-lifecycle-support:3.4.0:*:*:*:*:*:*:*"]
    id = "tomcat-lifecycle-support"
    name = "Apache Tomcat Lifecycle Support"
    purl = "pkg:generic/tomcat-lifecycle-support@3.4.0"
    sha256 = "3861d32a91b58302fa936d6f84354e1874f71e59dd97b003efcc992a5a6f3c47"
    source = "https://repo1.maven.org/maven2/org/cloudfoundry/tomcat-lifecycle-support/3.4.0.RELEASE/tomcat-lifecycle-support-3.4.0.RELEASE-sources.jar"
    source-sha256 = "a07fe091b4159825e1150249ad325f4ac018976b4c05ebc0e47b3e9bf021035e"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/org/cloudfoundry/tomcat-lifecycle-support/3.4.0.RELEASE/tomcat-lifecycle-support-3.4.0.RELEASE.jar"
    version = "3.4.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/cloudfoundry/java-buildpack-support/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:cloudfoundry:tomcat-logging-support:3.4.0:*:*:*:*:*:*:*"]
    id = "tomcat-logging-support"
    name = "Apache Tomcat Logging Support"
    purl = "pkg:generic/tomcat-logging-support@3.4.0"
    sha256 = "07de9efe8dda4c67dec6183ec1d59953abf1372cd71fe276fc4598739bd70667"
    source = "https://repo1.maven.org/maven2/org/cloudfoundry/tomcat-logging-support/3.4.0.RELEASE/tomcat-logging-support-3.4.0.RELEASE-sources.jar"
    source-sha256 = "6f7e95e8d3b00b91e8266e683dc3b34d60b7687ec8a6ae10687daa43c94cf94d"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/org/cloudfoundry/tomcat-logging-support/3.4.0.RELEASE/tomcat-logging-support-3.4.0.RELEASE.jar"
    version = "3.4.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/cloudfoundry/java-buildpack-support/blob/main/LICENSE"

[[stacks]]
  id = "*"
